In [1]:
import numpy as np

In [2]:
A = np.array(
    [[1,1,0],
     [0,0,1],
     [1,0,0]]
)

In [5]:
A @ A

array([[1, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

In [4]:
A @ A @ A

array([[2, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])

#### 2. Graph metrics

In [6]:
A = np.array(
[[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]
)

In [13]:
A.diagonal().sum() == 0 #Simple graph

True

In [14]:
(A == A.T).all() #Undirected

True

In [15]:
A.sum(0)

array([3, 4, 1, 5, 3, 2, 1, 1, 3, 3])

In [21]:
A @ A.T @ A.T @ A.T #l=4

array([[19, 14,  7, 21, 12, 11,  2,  7, 11,  5],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [ 7,  2,  4, 10,  7,  2,  1,  1,  2,  2],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [12,  6,  7, 20, 18,  4,  5,  2,  9,  9],
       [11, 17,  2, 11,  4, 12,  1,  7, 11,  4],
       [ 2,  2,  1,  2,  5,  1,  3,  1,  5,  2],
       [ 7, 10,  1,  4,  2,  7,  1,  5,  8,  2],
       [11, 19,  2,  8,  9, 11,  5,  8, 19,  9],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13]])

In [22]:
from scipy.sparse.csgraph import connected_components
connected_components(A)

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


(1, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [24]:
A.sum(0).max() #max deg

5

In [25]:
A @ A.T @ A.T @ A.T @ A.T

array([[46, 59, 14, 62, 30, 40,  5, 21, 38, 25],
       [59, 36, 28, 88, 57, 28, 10, 14, 30, 27],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [62, 88, 14, 58, 33, 58, 11, 37, 68, 30],
       [30, 57,  6, 33, 24, 32,  9, 20, 47, 32],
       [40, 28, 17, 58, 32, 22,  4, 11, 19, 16],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [38, 30, 19, 68, 47, 19,  9,  8, 26, 33],
       [25, 27, 10, 30, 32, 16, 13, 11, 33, 20]])

---

#### Graph metrics pt2

In [30]:
edge_list = np.loadtxt('release_directed_graph.txt').astype(int)

In [31]:
edge_list[:,0].max(), edge_list[:,1].max() #N nodes = 100

(99, 99)

In [32]:
edge_list.shape #edges

(1030, 2)

In [36]:
A = np.zeros((edge_list[:,0].max()+1,edge_list[:,0].max()+1))

for i in range(edge_list.shape[0]):
    A[edge_list[i,0],edge_list[i,1]] = 1

In [38]:
A.diagonal().sum() == 0

False

In [41]:
A.sum(0).min()

3.0

In [45]:
ratio = edge_list.shape[0]/((edge_list[:,0].max()+1)**2)
ratio

0.103

---

#### Modularity

In [86]:
A = np.array(
[[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]
)

In [87]:
def type(x):
    if x in [0,2,4,6,8]:
        return 1
    else:
        return 2

In [101]:
degs = A.sum(0)
n_edges = A.sum()/2

In [102]:
degs

array([3, 4, 1, 5, 3, 2, 1, 1, 3, 3])

In [103]:
(A[1,1] - (degs[1]*degs[1])/(2*n_edges))*(1*(type(1)==type(1)))

-0.6153846153846154

In [104]:
### modularity
mod = 0
for i in range(10):
    for j in range(10):
        mod = mod +  (A[i,j] - (degs[i]*degs[j])/(2*n_edges))*(1*(type(i)==type(j)))
mod = mod/(2*n_edges)

In [105]:
mod

-0.2041420118343195

---

#### Eigenvector centrality

In [108]:
import networkx as nx

In [109]:
A = np.array(
[[1,0,0,0],
[1,0,0,0],
[1,0,0,0],
[1,0,0,0]]
)

In [110]:
A.sum(0)

array([4, 0, 0, 0])

In [111]:
G=nx.from_numpy_matrix(A,create_using=nx.DiGraph())

In [112]:
nx.eigenvector_centrality(G)

{0: 0.9999999999986358,
 1: 9.536770448968607e-07,
 2: 9.536770448968607e-07,
 3: 9.536770448968607e-07}

In [113]:
A = np.array(
[[1,1,1,1],
[0,0,0,0],
[0,0,0,0],
[0,0,0,0]]
)

In [116]:
A.sum(0)

array([1, 1, 1, 1])

In [117]:
G=nx.from_numpy_matrix(A,create_using=nx.DiGraph())

In [118]:
nx.eigenvector_centrality(G)

{0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5}

In [119]:
A = np.array(
[[1,1,1,1],
[1,0,0,0],
[1,0,0,0],
[1,0,0,0]]
)

In [120]:
G=nx.from_numpy_matrix(A,create_using=nx.DiGraph())

In [121]:
nx.eigenvector_centrality(G)

{0: 0.7991714905460789,
 1: 0.34704703269074766,
 2: 0.34704703269074766,
 3: 0.34704703269074766}