In [1]:
import numpy as np

In [2]:
matrix = np.array([
    [8,4,7],
    [2,8,1],
    [3,1,1],
    [9,7,4]
])

In [3]:
matrix.mean(0)

array([5.5 , 5.  , 3.25])

In [21]:
def covariance(X: np.array):
    n = matrix.shape[0]
    return 1/n* X.T@ (np.identity(n) - 1/n*np.ones((n,n))) @ X

In [22]:
covariance(matrix)

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

#### orthogonal projection

In [23]:
n=3
H = np.identity(n) - 1/n*(np.ones((n,n)))

In [36]:
H

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [28]:
x = np.array([2,-1,-2])

In [30]:
(H@x)

array([ 2.33333333, -0.66666667, -1.66666667])

In [35]:
(H@H.T) @ x

array([ 2.33333333, -0.66666667, -1.66666667])

#### projection

In [54]:
u = 1/np.sqrt(5) * np.array([1,2])

In [55]:
data = np.array([
    [1,2],
    [3,4],
    [-1,0]
])

In [56]:
u = u.reshape(1,-1)

In [115]:
np.sum(u*data, axis=1, keepdims=True)*u #projections

array([[ 1. ,  2. ],
       [ 2.2,  4.4],
       [-0.2, -0.4]])

In [ ]:
#empirical distance u*Xi

In [124]:
## part 1
projections = np.sum(u*data, axis=1, keepdims=True).flatten()

In [125]:
1/n * projections.T @ (np.identity(n) - 1/n*np.ones((n,n))) @ projections

4.800000000000001

In [119]:
n = data.shape[0]
S = 1/n * data.T @ (np.identity(n) - 1/n*np.ones((n,n))) @ data #cov

In [120]:
S

array([[2.66666667, 2.66666667],
       [2.66666667, 2.66666667]])

In [121]:
S.shape

(2, 2)

In [122]:
u.shape

(1, 2)

In [123]:
###part2

u @ S @ u.T

array([[4.8]])