In [1]:
import numpy as np

In [2]:
matrix = np.array([
    [8,4,7],
    [2,8,1],
    [3,1,1],
    [9,7,4]
])

In [3]:
matrix.mean(0)

array([5.5 , 5.  , 3.25])

In [4]:
def covariance(X: np.array):
    n = matrix.shape[0]
    return 1/n* X.T@ (np.identity(n) - 1/n*np.ones((n,n))) @ X

In [5]:
covariance(matrix)

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

#### orthogonal projection

In [6]:
n=3
H = np.identity(n) - 1/n*(np.ones((n,n)))

In [7]:
H

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

In [8]:
x = np.array([2,-1,-2])

In [9]:
(H@x)

array([ 2.33333333, -0.66666667, -1.66666667])

In [10]:
(H@H.T) @ x

array([ 2.33333333, -0.66666667, -1.66666667])

#### projection

In [11]:
u = 1/np.sqrt(5) * np.array([1,2])

In [12]:
data = np.array([
    [1,2],
    [3,4],
    [-1,0]
])

In [13]:
u = u.reshape(1,-1)

In [14]:
np.sum(u*data, axis=1, keepdims=True)*u #projections

array([[ 1. ,  2. ],
       [ 2.2,  4.4],
       [-0.2, -0.4]])

In [15]:
#empirical distance u*Xi

In [16]:
## part 1
projections = np.sum(u*data, axis=1, keepdims=True).flatten()

In [17]:
1/n * projections.T @ (np.identity(n) - 1/n*np.ones((n,n))) @ projections

4.800000000000001

In [18]:
n = data.shape[0]
S = 1/n * data.T @ (np.identity(n) - 1/n*np.ones((n,n))) @ data #cov

In [19]:
S

array([[2.66666667, 2.66666667],
       [2.66666667, 2.66666667]])

In [20]:
S.shape

(2, 2)

In [21]:
u.shape

(1, 2)

In [22]:
###part2

u @ S @ u.T

array([[4.8]])

---

In [23]:
### 9.
X = np.array([
    [0,1],
    [0,-1]
])

In [24]:
n= 2

S = 1/n * X.T @ X

In [26]:
np.linalg.eig(S)

(array([0., 1.]),
 array([[1., 0.],
        [0., 1.]]))

In [25]:
S

array([[0., 0.],
       [0., 1.]])

In [40]:
### optional 10.
X = np.array([
    [1, 0.5],
    [-1,-0.5]
])

n= 1

S = 1/n * X.T @ X

In [41]:
S

array([[2. , 1. ],
       [1. , 0.5]])

In [43]:
eig_vals, eig_vec = np.linalg.eig(S)

eig_vec = eig_vec.T

In [49]:
np.inner(X[0], eig_vec[0])

1.118033988749895

In [50]:
np.inner(X[1], eig_vec[0])


-1.118033988749895

In [51]:
### 11. Optional
### optional 10.
X = np.array([
    [0,2],
    [1,-1],
    [-1,-1]
])

n= X.shape[0]

S = 1/n * X.T @ X

In [52]:
S

array([[0.66666667, 0.        ],
       [0.        , 2.        ]])

In [53]:
eig_vals, eig_vec = np.linalg.eig(S)

eig_vec = eig_vec.T
eig_vals

array([0.66666667, 2.        ])

In [73]:
PC1 = eig_vec[1].reshape(1,-1)

In [74]:
X.shape

(3, 2)

In [75]:
PC1.shape

(1, 2)

In [79]:
(X*PC1).sum(1)

array([ 2., -1., -1.])

In [80]:
np.var((X*PC1).sum(1))

2.0

In [81]:
### 12. Optional

X = np.array([
    [0,2],
    [0,-2],
    [1,1],
    [-1,-1],
])

n= X.shape[0]

S = 1/n * X.T @ X

In [83]:
eig_vals, eig_vec = np.linalg.eig(S)

eig_vec = eig_vec.T
eig_vals

array([0.38196601, 2.61803399])

In [85]:
eig_vec

array([[-0.97324899,  0.22975292],
       [-0.22975292, -0.97324899]])

#### MDS

In [86]:
X = np.array([
    [1,1],
    [1,-1],
    [-1,1]
])

In [88]:
B = X @ X.T
B

array([[ 2,  0,  0],
       [ 0,  2, -2],
       [ 0, -2,  2]])

In [103]:
eig_values, eig_vec = np.linalg.eig(B)

In [114]:
eig_values

array([4.0000000e+00, 4.4408921e-16, 2.0000000e+00])

In [120]:
eig_vec @ np.sqrt((np.identity(3)*eig_values))[:,0] #projection to 1d

array([ 0.        , -1.41421356,  1.41421356])